site_name: Спринт - 1
theme:
  name: material
nav:
  - Задание - 1: task1.md
  - Задание - 2: task2.md
  - Задание - 3: task3.md
  - Задание - 4: task4.md
plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
  - swagger-ui-tag